#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jun 07, 2017 11:28:25 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import wallet01_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    wallet01_support.set_Tk_var()
    top = Wallet_and_Transaction (root)
    wallet01_support.init(root, top)
    root.mainloop()

w = None
def create_Wallet_and_Transaction(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    wallet01_support.set_Tk_var()
    top = Wallet_and_Transaction (w)
    wallet01_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Wallet_and_Transaction():
    global w
    w.destroy()
    w = None


class Wallet_and_Transaction:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        top.geometry("768x647+419+26")
        top.title("Wallet and Transaction")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Labelframe2 = LabelFrame(top)
        self.Labelframe2.place(relx=0.04, rely=0.02, relheight=0.52
                , relwidth=0.94)
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Wallet''')
        self.Labelframe2.configure(background="#d9d9d9")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")
        self.Labelframe2.configure(width=720)

        self.lblBalance = Label(self.Labelframe2)
        self.lblBalance.place(relx=0.03, rely=0.19, height=26, width=166)
        self.lblBalance.configure(activebackground="#f9f9f9")
        self.lblBalance.configure(activeforeground="black")
        self.lblBalance.configure(background="#ffff80")
        self.lblBalance.configure(disabledforeground="#a3a3a3")
        self.lblBalance.configure(foreground="#000000")
        self.lblBalance.configure(highlightbackground="#d9d9d9")
        self.lblBalance.configure(highlightcolor="black")
        self.lblBalance.configure(justify=RIGHT)
        self.lblBalance.configure(relief=GROOVE)
        self.lblBalance.configure(text='''Balance''')
        self.lblBalance.configure(textvariable=wallet01_support.dataBalance)

        self.btnUpdateBalance1 = Button(self.Labelframe2)
        self.btnUpdateBalance1.place(relx=0.03, rely=0.07, height=33, width=166)
        self.btnUpdateBalance1.configure(activebackground="#d9d9d9")
        self.btnUpdateBalance1.configure(activeforeground="#000000")
        self.btnUpdateBalance1.configure(background="#d9d9d9")
        self.btnUpdateBalance1.configure(command=wallet01_support.onClick_btnUpdateBalance)
        self.btnUpdateBalance1.configure(disabledforeground="#a3a3a3")
        self.btnUpdateBalance1.configure(foreground="#000000")
        self.btnUpdateBalance1.configure(highlightbackground="#d9d9d9")
        self.btnUpdateBalance1.configure(highlightcolor="black")
        self.btnUpdateBalance1.configure(pady="0")
        self.btnUpdateBalance1.configure(text='''Update Balance''')

        self.btnSendGeneChainCoin = Button(self.Labelframe2)
        self.btnSendGeneChainCoin.place(relx=0.03, rely=0.75, height=33
                , width=166)
        self.btnSendGeneChainCoin.configure(activebackground="#d9d9d9")
        self.btnSendGeneChainCoin.configure(activeforeground="#000000")
        self.btnSendGeneChainCoin.configure(background="#d9d9d9")
        self.btnSendGeneChainCoin.configure(command=wallet01_support.onClick_btnSendGeneChainCoin)
        self.btnSendGeneChainCoin.configure(disabledforeground="#a3a3a3")
        self.btnSendGeneChainCoin.configure(foreground="#000000")
        self.btnSendGeneChainCoin.configure(highlightbackground="#d9d9d9")
        self.btnSendGeneChainCoin.configure(highlightcolor="black")
        self.btnSendGeneChainCoin.configure(pady="0")
        self.btnSendGeneChainCoin.configure(text='''Send GeneChainCoin''')

        self.entSendGeneChainCoin = Entry(self.Labelframe2)
        self.entSendGeneChainCoin.place(relx=0.03, rely=0.87, relheight=0.07
                , relwidth=0.23)
        self.entSendGeneChainCoin.configure(background="white")
        self.entSendGeneChainCoin.configure(disabledforeground="#a3a3a3")
        self.entSendGeneChainCoin.configure(font="TkFixedFont")
        self.entSendGeneChainCoin.configure(foreground="#000000")
        self.entSendGeneChainCoin.configure(highlightbackground="#d9d9d9")
        self.entSendGeneChainCoin.configure(highlightcolor="black")
        self.entSendGeneChainCoin.configure(insertbackground="black")
        self.entSendGeneChainCoin.configure(selectbackground="#c4c4c4")
        self.entSendGeneChainCoin.configure(selectforeground="black")
        self.entSendGeneChainCoin.configure(textvariable=wallet01_support.dataSendGeneChainCoin)

        self.lstSendGeneChainCoinAddress = Listbox(self.Labelframe2)
        self.lstSendGeneChainCoinAddress.place(relx=0.28, rely=0.06
                , relheight=0.89, relwidth=0.7)
        self.lstSendGeneChainCoinAddress.configure(background="white")
        self.lstSendGeneChainCoinAddress.configure(disabledforeground="#a3a3a3")
        self.lstSendGeneChainCoinAddress.configure(font="TkFixedFont")
        self.lstSendGeneChainCoinAddress.configure(foreground="#000000")
        self.lstSendGeneChainCoinAddress.configure(highlightbackground="#d9d9d9")
        self.lstSendGeneChainCoinAddress.configure(highlightcolor="black")
        self.lstSendGeneChainCoinAddress.configure(selectbackground="#c4c4c4")
        self.lstSendGeneChainCoinAddress.configure(selectforeground="black")
        self.lstSendGeneChainCoinAddress.configure(width=504)
        self.lstSendGeneChainCoinAddress.configure(listvariable=wallet01_support.datalstSendDataChainCoinAddress)
        self.lstSendGeneChainCoinAddress.bind('<ButtonRelease-1>',lambda e:wallet01_support.onBtn1Rls_lstSendGeneChainCoinAddress(e))

        self.btnWalletCreate1 = Button(self.Labelframe2)
        self.btnWalletCreate1.place(relx=0.03, rely=0.39, height=33, width=166)
        self.btnWalletCreate1.configure(activebackground="#d9d9d9")
        self.btnWalletCreate1.configure(activeforeground="#000000")
        self.btnWalletCreate1.configure(background="#d9d9d9")
        self.btnWalletCreate1.configure(command=wallet01_support.onClick_btnCreateWallet)
        self.btnWalletCreate1.configure(disabledforeground="#a3a3a3")
        self.btnWalletCreate1.configure(foreground="#000000")
        self.btnWalletCreate1.configure(highlightbackground="#d9d9d9")
        self.btnWalletCreate1.configure(highlightcolor="black")
        self.btnWalletCreate1.configure(pady="0")
        self.btnWalletCreate1.configure(text='''Create Wallet''')

        self.btnCreateNewAddress1 = Button(self.Labelframe2)
        self.btnCreateNewAddress1.place(relx=0.03, rely=0.27, height=33
                , width=166)
        self.btnCreateNewAddress1.configure(activebackground="#d9d9d9")
        self.btnCreateNewAddress1.configure(activeforeground="#000000")
        self.btnCreateNewAddress1.configure(background="#d9d9d9")
        self.btnCreateNewAddress1.configure(command=wallet01_support.onClick_btnCreateNewAddress)
        self.btnCreateNewAddress1.configure(disabledforeground="#a3a3a3")
        self.btnCreateNewAddress1.configure(foreground="#000000")
        self.btnCreateNewAddress1.configure(highlightbackground="#d9d9d9")
        self.btnCreateNewAddress1.configure(highlightcolor="black")
        self.btnCreateNewAddress1.configure(pady="0")
        self.btnCreateNewAddress1.configure(text='''Create New Address''')

        self.btnChargeWallet1 = Button(self.Labelframe2)
        self.btnChargeWallet1.place(relx=0.03, rely=0.51, height=33, width=166)
        self.btnChargeWallet1.configure(activebackground="#d9d9d9")
        self.btnChargeWallet1.configure(activeforeground="#000000")
        self.btnChargeWallet1.configure(background="#d9d9d9")
        self.btnChargeWallet1.configure(command=wallet01_support.onClick_btnChargeWallet)
        self.btnChargeWallet1.configure(disabledforeground="#a3a3a3")
        self.btnChargeWallet1.configure(foreground="#000000")
        self.btnChargeWallet1.configure(highlightbackground="#d9d9d9")
        self.btnChargeWallet1.configure(highlightcolor="black")
        self.btnChargeWallet1.configure(pady="0")
        self.btnChargeWallet1.configure(text='''Charge Wallet''')

        self.entChargeWallet1 = Entry(self.Labelframe2)
        self.entChargeWallet1.place(relx=0.03, rely=0.63, relheight=0.07
                , relwidth=0.23)
        self.entChargeWallet1.configure(background="white")
        self.entChargeWallet1.configure(disabledforeground="#a3a3a3")
        self.entChargeWallet1.configure(font="TkFixedFont")
        self.entChargeWallet1.configure(foreground="#000000")
        self.entChargeWallet1.configure(highlightbackground="#d9d9d9")
        self.entChargeWallet1.configure(highlightcolor="black")
        self.entChargeWallet1.configure(insertbackground="black")
        self.entChargeWallet1.configure(selectbackground="#c4c4c4")
        self.entChargeWallet1.configure(selectforeground="black")
        self.entChargeWallet1.configure(textvariable=wallet01_support.dataChargeWallet)

        self.Labelframe3 = LabelFrame(top)
        self.Labelframe3.place(relx=0.04, rely=0.54, relheight=0.38
                , relwidth=0.94)
        self.Labelframe3.configure(relief=GROOVE)
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Transactions''')
        self.Labelframe3.configure(background="#d9d9d9")
        self.Labelframe3.configure(highlightbackground="#d9d9d9")
        self.Labelframe3.configure(highlightcolor="black")
        self.Labelframe3.configure(width=720)

        self.lstTransaction = Listbox(self.Labelframe3)
        self.lstTransaction.place(relx=0.01, rely=0.08, relheight=0.85
                , relwidth=0.96)
        self.lstTransaction.configure(background="white")
        self.lstTransaction.configure(disabledforeground="#a3a3a3")
        self.lstTransaction.configure(font="TkFixedFont")
        self.lstTransaction.configure(foreground="#000000")
        self.lstTransaction.configure(highlightbackground="#d9d9d9")
        self.lstTransaction.configure(highlightcolor="black")
        self.lstTransaction.configure(selectbackground="#c4c4c4")
        self.lstTransaction.configure(selectforeground="black")
        self.lstTransaction.configure(width=694)
        self.lstTransaction.configure(listvariable=wallet01_support.datalstTransaction)
        self.lstTransaction.bind('<ButtonRelease-1>',lambda e:wallet01_support.onBtn1Rls_lstTransaction(e))

        self.btnExit = Button(top)
        self.btnExit.place(relx=0.77, rely=0.93, height=33, width=156)
        self.btnExit.configure(activebackground="#d9d9d9")
        self.btnExit.configure(activeforeground="#000000")
        self.btnExit.configure(background="#d9d9d9")
        self.btnExit.configure(command=wallet01_support.onClick_btnExit)
        self.btnExit.configure(disabledforeground="#a3a3a3")
        self.btnExit.configure(foreground="#000000")
        self.btnExit.configure(highlightbackground="#d9d9d9")
        self.btnExit.configure(highlightcolor="black")
        self.btnExit.configure(pady="0")
        self.btnExit.configure(text='''Exit''')






if __name__ == '__main__':
    vp_start_gui()



